version: '3.8'

services:
  backend-dev:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hospital-backend-dev-cloud
    ports:
      - "8060:8080"
    environment:
      - QUARKUS_PROFILE=dev
      - DB_HOST=35.208.14.178
      - DB_PORT=1521
      - DB_NAME=XE
      - DB_USER=C##HOSPITAL
      - DB_PASSWORD=hospital123
    restart: unless-stopped

  frontend-dev:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: hospital-frontend-dev-cloud
    ports:
      - "8061:80"
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://34.61.228.49:8060
    restart: unless-stopped