services:
  # Base de datos Oracle - Comentado porque ya existe un contenedor
  # oracle:
  #   image: oracle-xe-con-datos:latest
  #   container_name: oracle-xe
  #   environment:
  #     ORACLE_PWD: Unis
  #     ORACLE_CHARACTERSET: AL32UTF8
  #   ports:
  #     - "1524:1521"  # Mapeo del puerto 1524 externo al 1521 interno
  #   volumes:
  #     - oracle_data:/opt/oracle/oradata
  #     - ./setup-oracle-users.sql:/opt/oracle/scripts/startup/setup-oracle-users.sql
  #   healthcheck:
  #     test: ["CMD", "sqlplus", "-L", "sys/Unis@//localhost:1521/XEPDB1", "AS", "SYSDBA", "@healthcheck.sql"]
  #     interval: 30s
  #     timeout: 10s
  #     retries: 5
  #   networks:
  #     - hospital-network

  # Backend del Hospital
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hospital-backend-prod
    ports:
      - "8060:8080"
    # depends_on:
    #   oracle:
    #     condition: service_healthy
    restart: unless-stopped
    networks:
      - hospital-network

  # Frontend del Hospital
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: hospital-frontend-prod
    environment:
      VITE_API_URL: http://localhost:8060
      NODE_ENV: production
    ports:
      - "5176:80"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - hospital-network

# volumes:
#   oracle_data:

networks:
  hospital-network:
    driver: bridge
