services:
  # Base de datos Oracle para PRODUCCIÓN
  oracle:
    image: container-registry.oracle.com/database/express:21.3.0-xe
    container_name: hospital-oracle-prod
    environment:
      ORACLE_PWD: Unis
      ORACLE_CHARACTERSET: AL32UTF8
    ports:
      - "1521:1521"  # Puerto estándar para producción
    volumes:
      - oracle_prod_data:/opt/oracle/oradata
      - ./backend/src/main/resources/import.sql:/opt/oracle/scripts/startup/import.sql
    healthcheck:
      test: ["CMD", "sqlplus", "-L", "Hospital3/Unis@localhost:1521/XEPDB1", "@healthcheck.sql"]
      interval: 30s
      timeout: 10s
      retries: 5

  # Backend del Hospital para PRODUCCIÓN
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: hospital-backend-prod
    environment:
      QUARKUS_DATASOURCE_URL: jdbc:oracle:thin:@oracle:1521/XEPDB1
      QUARKUS_DATASOURCE_USERNAME: Hospital3
      QUARKUS_DATASOURCE_PASSWORD: Unis
      QUARKUS_HTTP_PORT: 8080
      QUARKUS_PROFILE: prod
    ports:
      - "8084:8080"  # Puerto de producción
    depends_on:
      oracle:
        condition: service_healthy
    volumes:
      - ./backend/src/main/resources/application.properties:/app/config/application.properties
    restart: unless-stopped

  # Frontend del Hospital para PRODUCCIÓN
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: hospital-frontend-prod
    environment:
      VITE_API_URL: http://localhost:8084
      NODE_ENV: production
    ports:
      - "5176:80"  # Puerto de producción
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  oracle_prod_data:
