version: '3.8'

services:
  # Backend Quarkus para QA (usando Oracle compartido)
  backend-qa:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hospital-backend-qa
    environment:
      QUARKUS_DATASOURCE_URL: jdbc:oracle:thin:@oracle:1521/XE
      QUARKUS_DATASOURCE_USERNAME: Hospital2
      QUARKUS_DATASOURCE_PASSWORD: Unis
      QUARKUS_HTTP_PORT: 8080
      QUARKUS_PROFILE: qa
    ports:
      - "8082:8080"  # Puerto diferente para QA
    depends_on:
      - oracle
    volumes:
      - ./backend/src/main/resources/application.properties:/app/config/application.properties
      - ./backend/src/main/resources/application-qa.properties:/app/config/application-qa.properties
    restart: unless-stopped
    external_links:
      - hospital-oracle-xe:oracle

  # Frontend Vue.js para QA
  frontend-qa:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: hospital-frontend-qa
    environment:
      VITE_API_URL: http://localhost:8082
      NODE_ENV: qa
    ports:
      - "5175:80"  # Puerto diferente para QA
    depends_on:
      - backend-qa
    restart: unless-stopped

  # Nginx reverse proxy para QA
  nginx-qa:
    image: nginx:alpine
    container_name: hospital-nginx-qa
    ports:
      - "8083:80"
    volumes:
      - ./nginx.qa.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend-qa
      - backend-qa
    restart: unless-stopped 