version: '3.8'

services:
  sonarqube:
    image: sonarqube:10.4.1-community
    container_name: sonarqube
    ports:
      - "9000:9000"
    environment:
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
      - SONAR_WEB_JVMOPTS=-Xmx512m -Xms128m
      - SONAR_SEARCH_JVMOPTS=-Xmx512m -Xms128m
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/api/system/status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

volumes:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
