version: '3.8'

services:
  backend-qa:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hospital-backend-qa-cloud
    ports:
      - "8030:8080"
    environment:
      - QUARKUS_PROFILE=qa
      - DB_HOST=35.208.14.178
      - DB_PORT=1522
      - DB_NAME=XE
      - DB_USER=C##HOSPITAL
      - DB_PASSWORD=hospital123
    restart: unless-stopped

  frontend-qa:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: hospital-frontend-qa-cloud
    ports:
      - "8031:80"
    environment:
      - NODE_ENV=production
      - VITE_API_URL=http://34.61.228.49:8030
    restart: unless-stopped