version: '3.8'

services:
  # Backend Quarkus para DESARROLLO (usando Oracle compartido)
  backend-dev:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hospital-backend-dev
    environment:
      QUARKUS_DATASOURCE_URL: jdbc:oracle:thin:@oracle:1521/XE
      QUARKUS_DATASOURCE_USERNAME: C##PROYECTO
      QUARKUS_DATASOURCE_PASSWORD: Unis
      QUARKUS_HTTP_PORT: 8080
      QUARKUS_PROFILE: dev
    ports:
      - "8081:8080"  # Puerto diferente para desarrollo
    depends_on:
      - oracle
    volumes:
      - ./backend/src/main/resources/application.properties:/app/config/application.properties
      - ./backend/src/main/resources/application-dev.properties:/app/config/application-dev.properties
    restart: unless-stopped
    external_links:
      - hospital-oracle-xe:oracle

  # Frontend Vue.js para DESARROLLO
  frontend-dev:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: hospital-frontend-dev
    environment:
      VITE_API_URL: http://localhost:8081
      NODE_ENV: development
    ports:
      - "5173:80"  # Puerto diferente para desarrollo
    depends_on:
      - backend-dev
    restart: unless-stopped

  # Nginx reverse proxy para DESARROLLO
  nginx-dev:
    image: nginx:alpine
    container_name: hospital-nginx-dev
    ports:
      - "8085:80"
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend-dev
      - backend-dev
    restart: unless-stopped

  # Monitoreo para DESARROLLO
  prometheus-dev:
    image: prom/prometheus:latest
    container_name: hospital-prometheus-dev
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    restart: unless-stopped

  # Grafana para dashboards en DESARROLLO
  grafana-dev:
    image: grafana/grafana:latest
    container_name: hospital-grafana-dev
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin123
    volumes:
      - grafana_dev_data:/var/lib/grafana
    restart: unless-stopped

volumes:
  grafana_dev_data:
