version: '3.8'

services:
  # Base de datos Oracle para QA
  oracle-qa:
    image: container-registry.oracle.com/database/express:21.3.0-xe
    container_name: hospital-oracle-qa
    environment:
      ORACLE_PWD: Unis
      ORACLE_CHARACTERSET: AL32UTF8
    ports:
      - "1522:1521"  # Puerto diferente para QA
    volumes:
      - oracle_qa_data:/opt/oracle/oradata
      - ./backend/src/main/resources/import.sql:/opt/oracle/scripts/startup/import.sql
    healthcheck:
      test: ["CMD", "sqlplus", "-L", "HOSPITAL2/Unis@localhost:1521/XEPDB1", "@healthcheck.sql"]
      interval: 30s
      timeout: 10s
      retries: 5

  # Backend Quarkus para QA
  backend-qa:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hospital-backend-qa
    environment:
      QUARKUS_DATASOURCE_URL: jdbc:oracle:thin:@oracle-qa:1521/XEPDB1
      QUARKUS_DATASOURCE_USERNAME: HOSPITAL2
      QUARKUS_DATASOURCE_PASSWORD: Unis
      QUARKUS_HTTP_PORT: 8080
      QUARKUS_PROFILE: qa
    ports:
      - "8082:8080"  # Puerto diferente para QA
    depends_on:
      oracle-qa:
        condition: service_healthy
    volumes:
      - ./backend/src/main/resources/application-qa.properties:/app/config/application.properties
    restart: unless-stopped

  # Frontend Vue.js para QA
  frontend-qa:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: hospital-frontend-qa
    environment:
      VITE_API_URL: http://localhost:8082
      NODE_ENV: qa
    ports:
      - "5175:80"  # Puerto diferente para QA
    depends_on:
      - backend-qa
    restart: unless-stopped

  # Nginx reverse proxy para QA
  nginx-qa:
    image: nginx:alpine
    container_name: hospital-nginx-qa
    ports:
      - "8083:80"
    volumes:
      - ./nginx.qa.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend-qa
      - backend-qa
    restart: unless-stopped

volumes:
  oracle_qa_data: 