version: '3.8'

services:
  # Backend Quarkus para DESARROLLO
  hospital-backend-dev:
    build:
      context: ./backend
      dockerfile: Dockerfile.jvm
    container_name: hospital-backend-dev
    environment:
      QUARKUS_DATASOURCE_URL: jdbc:oracle:thin:@oracle_xe:1521/XEPDB1
      QUARKUS_DATASOURCE_USERNAME: C##PROYECTO
      QUARKUS_DATASOURCE_PASSWORD: Unis
      QUARKUS_HTTP_PORT: 8080
      QUARKUS_PROFILE: dev
    ports:
      - "8060:8080"  # Puerto específico para DEV
    restart: unless-stopped
    network_mode: "bridge"
    external_links:
      - oracle_xe:oracle_xe

  # Frontend Vue.js para DESARROLLO
  hospital-frontend-dev:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: hospital-frontend-dev
    environment:
      VITE_API_URL: http://localhost:8060
      NODE_ENV: development
    ports:
      - "5180:80"  # Puerto específico para DEV
    restart: unless-stopped
    depends_on:
      - hospital-backend-dev
