version: '3.8'

services:
  # Base de datos Oracle (para desarrollo local)
  oracle:
    image: oracle-xe-con-datos:latest
    environment:
      ORACLE_PWD: Unis
      ORACLE_CHARACTERSET: AL32UTF8
    ports:
      - "1521:1521"
    volumes:
      - oracle_data:/opt/oracle/oradata
    healthcheck:
      test: ["CMD", "sqlplus", "-L", "sys/Unis@//localhost:1521/XE", "AS", "SYSDBA", "@healthcheck.sql"]
      interval: 30s
      timeout: 10s
      retries: 5

  # Backend del Hospital
  backend:
    image: hospital-registry/hospital-backend:20
    ports:
      - "8080:8080"
    environment:
      - QUARKUS_DATASOURCE_JDBC_URL=jdbc:oracle:thin:@oracle:1521/XEPDB1
      - QUARKUS_DATASOURCE_USERNAME=C##PROYECTO
      - QUARKUS_DATASOURCE_PASSWORD=Unis
    depends_on:
      oracle:
        condition: service_healthy
    restart: unless-stopped

  # Frontend del Hospital
  frontend:
    image: hospital-registry/hospital-frontend:20
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  oracle_data:
