-- Script para corregir y crear usuarios en Oracle XE
-- Conectar como SYSDBA

-- Cambiar contraseña de C##PROYECTO
ALTER USER "C##PROYECTO" IDENTIFIED BY Unis;

-- Crear usuario HOSPITAL2_USER (nombre válido)
CREATE USER HOSPITAL2_USER IDENTIFIED BY Unis;

-- Crear usuario HOSPITAL3_USER (nombre válido)
CREATE USER HOSPITAL3_USER IDENTIFIED BY Unis;

-- Dar permisos completos a C##PROYECTO
GRANT CONNECT, RESOURCE, DBA, CREATE SESSION, CREATE TABLE, CREATE VIEW, CREATE PROCEDURE, CREATE SEQUENCE, CREATE TRIGGER, UNLIMITED TABLESPACE TO "C##PROYECTO";

-- Dar permisos completos a HOSPITAL2_USER
GRANT CONNECT, RESOURCE, DBA, CREATE SESSION, CREATE TABLE, CREATE VIEW, CREATE PROCEDURE, CREATE SEQUENCE, CREATE TRIGGER, UNLIMITED TABLESPACE TO HOSPITAL2_USER;

-- Dar permisos completos a HOSPITAL3_USER
GRANT CONNECT, RESOURCE, DBA, CREATE SESSION, CREATE TABLE, CREATE VIEW, CREATE PROCEDURE, CREATE SEQUENCE, CREATE TRIGGER, UNLIMITED TABLESPACE TO HOSPITAL3_USER;

-- Verificar usuarios creados
SELECT username, account_status FROM dba_users WHERE username IN ('C##PROYECTO', 'HOSPITAL2_USER', 'HOSPITAL3_USER');

-- Salir
EXIT;
