#!/bin/bash

echo "🔧 Instalando JUnit Plugin en Jenkins..."
echo ""
echo "📋 Pasos para instalar el JUnit Plugin:"
echo ""
echo "1. Abre Jenkins en tu navegador: http://localhost:8081"
echo ""
echo "2. Ve a 'Manage Jenkins' > 'Manage Plugins'"
echo ""
echo "3. Haz clic en la pestaña 'Available'"
echo ""
echo "4. Busca 'JUnit' en el campo de búsqueda"
echo ""
echo "5. Marca la casilla 'JUnit Plugin'"
echo ""
echo "6. Haz clic en 'Install without restart'"
echo ""
echo "7. Espera a que se complete la instalación"
echo ""
echo "8. Una vez instalado, ve a tu pipeline 'Hospital-CI-CD'"
echo ""
echo "9. Haz clic en 'Build Now' para ejecutar el pipeline nuevamente"
echo ""
echo "✅ El plugin JUnit permitirá que el pipeline publique los resultados de las pruebas"
echo ""
echo "🔍 Alternativamente, puedes instalar el plugin desde la línea de comandos:"
echo "   curl -X POST http://localhost:8081/pluginManager/installNecessaryPlugins -d '<jenkins><install plugin=junit@latest/></jenkins>'"
echo "" 